# Generated by Django 4.2.30 on 2026-09-22 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientGalleryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('service_received', models.CharField(max_length=150)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(help_text='Ej: $8.500', max_length=50)),
                ('price_num', models.IntegerField(help_text='Valor numérico para cálculos')),
                ('stock_status', models.CharField(default='Disponible', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(help_text='Ej: $15.000', max_length=50)),
                ('price_num', models.IntegerField(help_text='Valor numérico para cálculos')),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text='Ej: 1 hora, 45 min', max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=200, null=True)),
                ('image_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('pet_name_and_breed', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time_slot', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
        ),
    ]
